/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuggestRouteImport } from './routes/suggest'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompaniesSlugRouteImport } from './routes/companies/$slug'

const SuggestRoute = SuggestRouteImport.update({
  id: '/suggest',
  path: '/suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesSlugRoute = CompaniesSlugRouteImport.update({
  id: '/companies/$slug',
  path: '/companies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/suggest': typeof SuggestRoute
  '/companies/$slug': typeof CompaniesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/suggest': typeof SuggestRoute
  '/companies/$slug': typeof CompaniesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/suggest': typeof SuggestRoute
  '/companies/$slug': typeof CompaniesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/compare' | '/suggest' | '/companies/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/compare' | '/suggest' | '/companies/$slug'
  id: '__root__' | '/' | '/compare' | '/suggest' | '/companies/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  SuggestRoute: typeof SuggestRoute
  CompaniesSlugRoute: typeof CompaniesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suggest': {
      id: '/suggest'
      path: '/suggest'
      fullPath: '/suggest'
      preLoaderRoute: typeof SuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$slug': {
      id: '/companies/$slug'
      path: '/companies/$slug'
      fullPath: '/companies/$slug'
      preLoaderRoute: typeof CompaniesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  SuggestRoute: SuggestRoute,
  CompaniesSlugRoute: CompaniesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
